#!/bin/sh
pid=0

exit_script() {
  # Clear the trap
  trap - SIGTERM
  # Send SIGTERM to child/sub processes
  if [ $pid -ne 0 ]; then
    kill -SIGTERM "$pid"
    wait "$pid"
  fi
  exit 143;
}

trap 'kill ${!}; exit_script' SIGTERM

# Run tail
tail -n+1 -F ${LOG_GLOB} & pid="$!"

# Wait forever
while true
do
  tail -f /dev/null & wait ${!}
done
